/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mibs.asterisk.callboard;

import org.junit.Test;

import com.mibs.callboard.App;

import static org.junit.Assert.*;

public class AppTest {
	static String s0 = "hello";
    @Test public void testAppHasAGreeting() {
       // App classUnderTest = new App();
    	
        assertNotNull("app should have a greeting", s0);
    }
}
