/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mibs.asterisk.callboard;

import org.junit.Test;

import com.mibs.callboard.App;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App(null);
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
